low_ai_resistance = [
    # Knowledge
    "Knowledge: Building and Construction",
    "Knowledge: Food Production",
    "Knowledge: Mechanical",
    "Knowledge: Production and Processing",
    "Knowledge: Transportation",
    "Knowledge: Public Safety and Security",

    # Skills
    "Skill: Equipment Maintenance",
    "Skill: Equipment Selection",
    "Skill: Installation",
    "Skill: Operation and Control",
    "Skill: Operations Monitoring",
    "Skill: Repairing",

    # Abilities
    "Ability: Arm-Hand Steadiness",
    "Ability: Control Precision",
    "Ability: Depth Perception",
    "Ability: Dynamic Strength",
    "Ability: Explosive Strength",
    "Ability: Far Vision",
    "Ability: Finger Dexterity",
    "Ability: Gross Body Coordination",
    "Ability: Gross Body Equilibrium",
    "Ability: Manual Dexterity",
    "Ability: Multilimb Coordination",
    "Ability: Near Vision",
    "Ability: Night Vision",
    "Ability: Peripheral Vision",
    "Ability: Rate Control",
    "Ability: Reaction Time",
    "Ability: Speed of Limb Movement",
    "Ability: Stamina",
    "Ability: Static Strength",
    "Ability: Trunk Strength",
    "Ability: Wrist-Finger Speed"
]

medium_ai_resistance = [
    # Knowledge
    "Knowledge: Administration and Management",
    "Knowledge: Administrative",
    "Knowledge: Biology",
    "Knowledge: Chemistry",
    "Knowledge: Communications and Media",
    "Knowledge: Computers and Electronics",
    "Knowledge: Design",
    "Knowledge: Economics and Accounting",
    "Knowledge: Engineering and Technology",
    "Knowledge: English Language",
    "Knowledge: Fine Arts",
    "Knowledge: Foreign Language",
    "Knowledge: Geography",
    "Knowledge: History and Archeology",
    "Knowledge: Mathematics",
    "Knowledge: Medicine and Dentistry",
    "Knowledge: Physics",
    "Knowledge: Sales and Marketing",
    "Knowledge: Telecommunications",
    "Knowledge: Biology",
    "Knowledge: Chemistry",
    "Knowledge: Medicine and Dentistry",

    # Skills
    "Skill: Coordination",
    "Skill: Mathematics",
    "Skill: Monitoring",
    "Skill: Operations Analysis",
    "Skill: Programming",
    "Skill: Quality Control Analysis",
    "Skill: Reading Comprehension",
    "Skill: Science",
    "Skill: Speaking",
    "Skill: Systems Analysis",
    "Skill: Systems Evaluation",
    "Skill: Technology Design",
    "Skill: Time Management",
    "Skill: Troubleshooting",
    "Skill: Writing",

    # Abilities
    "Ability: Auditory Attention",
    "Ability: Category Flexibility",
    "Ability: Dynamic Flexibility",
    "Ability: Extent Flexibility",
    "Ability: Flexibility of Closure",
    "Ability: Glare Sensitivity",
    "Ability: Hearing Sensitivity",
    "Ability: Inductive Reasoning",
    "Ability: Information Ordering",
    "Ability: Mathematical Reasoning",
    "Ability: Memorization",
    "Ability: Number Facility",
    "Ability: Perceptual Speed",
    "Ability: Response Orientation",
    "Ability: Selective Attention",
    "Ability: Sound Localization",
    "Ability: Spatial Orientation",
    "Ability: Speech Clarity",
    "Ability: Speech Recognition",
    "Ability: Speed of Closure",
    "Ability: Visual Color Discrimination",
    "Ability: Visualization",
    "Ability: Written Comprehension",
    "Ability: Visual Color Discrimination",
    "Ability: Sound Localization",
    "Ability: Written Comprehension"
]

high_ai_resistance = [
    # Knowledge
    "Knowledge: Customer and Personal Service",
    "Knowledge: Education and Training",
    "Knowledge: Law and Government",
    "Knowledge: Personnel and Human Resources",
    "Knowledge: Philosophy and Theology",
    "Knowledge: Psychology",
    "Knowledge: Sociology and Anthropology",
    "Knowledge: Therapy and Counseling",

    # Skills
    "Skill: Active Learning",
    "Skill: Active Listening",
    "Skill: Complex Problem Solving",
    "Skill: Critical Thinking",
    "Skill: Instructing",
    "Skill: Judgment and Decision Making",
    "Skill: Learning Strategies",
    "Skill: Management of Financial Resources",
    "Skill: Management of Material Resources",
    "Skill: Management of Personnel Resources",
    "Skill: Negotiation",
    "Skill: Persuasion",
    "Skill: Service Orientation",
    "Skill: Social Perceptiveness",

    # Abilities
    "Ability: Deductive Reasoning",
    "Ability: Fluency of Ideas",
    "Ability: Oral Comprehension",
    "Ability: Oral Expression",
    "Ability: Originality",
    "Ability: Problem Sensitivity",
    "Ability: Time Sharing",
    "Ability: Written Expression"
]


